// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: message_struct.proto
// Protobuf C++ Version: 5.27.0

#include "message_struct.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr TestMsg::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : file_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        aes_key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iv_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ciphertext_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        magic_{0u},
        slice_index_{0u},
        total_slices_{0u},
        plaintext_size_{0u},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR TestMsg::TestMsg(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct TestMsgDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TestMsgDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~TestMsgDefaultTypeInternal() {}
  union {
    TestMsg _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TestMsgDefaultTypeInternal _TestMsg_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_message_5fstruct_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_message_5fstruct_2eproto = nullptr;
const ::uint32_t
    TableStruct_message_5fstruct_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::TestMsg, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.magic_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.slice_index_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.total_slices_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.plaintext_size_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.aes_key_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.file_id_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.iv_),
        PROTOBUF_FIELD_OFFSET(::TestMsg, _impl_.ciphertext_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::TestMsg)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_TestMsg_default_instance_._instance,
};
const char descriptor_table_protodef_message_5fstruct_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\024message_struct.proto\"\235\001\n\007TestMsg\022\r\n\005ma"
    "gic\030\002 \001(\r\022\023\n\013slice_index\030\003 \001(\r\022\024\n\014total_"
    "slices\030\004 \001(\r\022\026\n\016plaintext_size\030\010 \001(\r\022\017\n\007"
    "aes_key\030\005 \001(\014\022\017\n\007file_id\030\001 \001(\014\022\n\n\002iv\030\006 \001"
    "(\014\022\022\n\nciphertext\030\007 \001(\014b\006proto3"
};
static ::absl::once_flag descriptor_table_message_5fstruct_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_message_5fstruct_2eproto = {
    false,
    false,
    190,
    descriptor_table_protodef_message_5fstruct_2eproto,
    "message_struct.proto",
    &descriptor_table_message_5fstruct_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_message_5fstruct_2eproto::offsets,
    file_level_enum_descriptors_message_5fstruct_2eproto,
    file_level_service_descriptors_message_5fstruct_2eproto,
};
// ===================================================================

class TestMsg::_Internal {
 public:
};

TestMsg::TestMsg(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:TestMsg)
}
inline PROTOBUF_NDEBUG_INLINE TestMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::TestMsg& from_msg)
      : file_id_(arena, from.file_id_),
        aes_key_(arena, from.aes_key_),
        iv_(arena, from.iv_),
        ciphertext_(arena, from.ciphertext_),
        _cached_size_{0} {}

TestMsg::TestMsg(
    ::google::protobuf::Arena* arena,
    const TestMsg& from)
    : ::google::protobuf::Message(arena) {
  TestMsg* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, magic_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, magic_),
           offsetof(Impl_, plaintext_size_) -
               offsetof(Impl_, magic_) +
               sizeof(Impl_::plaintext_size_));

  // @@protoc_insertion_point(copy_constructor:TestMsg)
}
inline PROTOBUF_NDEBUG_INLINE TestMsg::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : file_id_(arena),
        aes_key_(arena),
        iv_(arena),
        ciphertext_(arena),
        _cached_size_{0} {}

inline void TestMsg::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, magic_),
           0,
           offsetof(Impl_, plaintext_size_) -
               offsetof(Impl_, magic_) +
               sizeof(Impl_::plaintext_size_));
}
TestMsg::~TestMsg() {
  // @@protoc_insertion_point(destructor:TestMsg)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void TestMsg::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.file_id_.Destroy();
  _impl_.aes_key_.Destroy();
  _impl_.iv_.Destroy();
  _impl_.ciphertext_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
TestMsg::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(TestMsg, _impl_._cached_size_),
              false,
          },
          &TestMsg::MergeImpl,
          &TestMsg::kDescriptorMethods,
          &descriptor_table_message_5fstruct_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 8, 0, 0, 2> TestMsg::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    8, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967040,  // skipmap
    offsetof(decltype(_table_), field_entries),
    8,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_TestMsg_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::TestMsg>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // uint32 plaintext_size = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg, _impl_.plaintext_size_), 63>(),
     {64, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.plaintext_size_)}},
    // bytes file_id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.file_id_)}},
    // uint32 magic = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg, _impl_.magic_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.magic_)}},
    // uint32 slice_index = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg, _impl_.slice_index_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.slice_index_)}},
    // uint32 total_slices = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(TestMsg, _impl_.total_slices_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.total_slices_)}},
    // bytes aes_key = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.aes_key_)}},
    // bytes iv = 6;
    {::_pbi::TcParser::FastBS1,
     {50, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.iv_)}},
    // bytes ciphertext = 7;
    {::_pbi::TcParser::FastBS1,
     {58, 63, 0, PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.ciphertext_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes file_id = 1;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.file_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 magic = 2;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.magic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 slice_index = 3;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.slice_index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 total_slices = 4;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.total_slices_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bytes aes_key = 5;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.aes_key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes iv = 6;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.iv_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes ciphertext = 7;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.ciphertext_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint32 plaintext_size = 8;
    {PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.plaintext_size_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void TestMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:TestMsg)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.file_id_.ClearToEmpty();
  _impl_.aes_key_.ClearToEmpty();
  _impl_.iv_.ClearToEmpty();
  _impl_.ciphertext_.ClearToEmpty();
  ::memset(&_impl_.magic_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.plaintext_size_) -
      reinterpret_cast<char*>(&_impl_.magic_)) + sizeof(_impl_.plaintext_size_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* TestMsg::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TestMsg)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes file_id = 1;
  if (!this->_internal_file_id().empty()) {
    const std::string& _s = this->_internal_file_id();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  // uint32 magic = 2;
  if (this->_internal_magic() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_magic(), target);
  }

  // uint32 slice_index = 3;
  if (this->_internal_slice_index() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_slice_index(), target);
  }

  // uint32 total_slices = 4;
  if (this->_internal_total_slices() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        4, this->_internal_total_slices(), target);
  }

  // bytes aes_key = 5;
  if (!this->_internal_aes_key().empty()) {
    const std::string& _s = this->_internal_aes_key();
    target = stream->WriteBytesMaybeAliased(5, _s, target);
  }

  // bytes iv = 6;
  if (!this->_internal_iv().empty()) {
    const std::string& _s = this->_internal_iv();
    target = stream->WriteBytesMaybeAliased(6, _s, target);
  }

  // bytes ciphertext = 7;
  if (!this->_internal_ciphertext().empty()) {
    const std::string& _s = this->_internal_ciphertext();
    target = stream->WriteBytesMaybeAliased(7, _s, target);
  }

  // uint32 plaintext_size = 8;
  if (this->_internal_plaintext_size() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        8, this->_internal_plaintext_size(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TestMsg)
  return target;
}

::size_t TestMsg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TestMsg)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // bytes file_id = 1;
  if (!this->_internal_file_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_file_id());
  }

  // bytes aes_key = 5;
  if (!this->_internal_aes_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_aes_key());
  }

  // bytes iv = 6;
  if (!this->_internal_iv().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_iv());
  }

  // bytes ciphertext = 7;
  if (!this->_internal_ciphertext().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_ciphertext());
  }

  // uint32 magic = 2;
  if (this->_internal_magic() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_magic());
  }

  // uint32 slice_index = 3;
  if (this->_internal_slice_index() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_slice_index());
  }

  // uint32 total_slices = 4;
  if (this->_internal_total_slices() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_total_slices());
  }

  // uint32 plaintext_size = 8;
  if (this->_internal_plaintext_size() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_plaintext_size());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void TestMsg::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<TestMsg*>(&to_msg);
  auto& from = static_cast<const TestMsg&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:TestMsg)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_file_id().empty()) {
    _this->_internal_set_file_id(from._internal_file_id());
  }
  if (!from._internal_aes_key().empty()) {
    _this->_internal_set_aes_key(from._internal_aes_key());
  }
  if (!from._internal_iv().empty()) {
    _this->_internal_set_iv(from._internal_iv());
  }
  if (!from._internal_ciphertext().empty()) {
    _this->_internal_set_ciphertext(from._internal_ciphertext());
  }
  if (from._internal_magic() != 0) {
    _this->_impl_.magic_ = from._impl_.magic_;
  }
  if (from._internal_slice_index() != 0) {
    _this->_impl_.slice_index_ = from._impl_.slice_index_;
  }
  if (from._internal_total_slices() != 0) {
    _this->_impl_.total_slices_ = from._impl_.total_slices_;
  }
  if (from._internal_plaintext_size() != 0) {
    _this->_impl_.plaintext_size_ = from._impl_.plaintext_size_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void TestMsg::CopyFrom(const TestMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TestMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void TestMsg::InternalSwap(TestMsg* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.file_id_, &other->_impl_.file_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.aes_key_, &other->_impl_.aes_key_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.iv_, &other->_impl_.iv_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.ciphertext_, &other->_impl_.ciphertext_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.plaintext_size_)
      + sizeof(TestMsg::_impl_.plaintext_size_)
      - PROTOBUF_FIELD_OFFSET(TestMsg, _impl_.magic_)>(
          reinterpret_cast<char*>(&_impl_.magic_),
          reinterpret_cast<char*>(&other->_impl_.magic_));
}

::google::protobuf::Metadata TestMsg::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_message_5fstruct_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
